# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import garrison_pb2 as garrison__pb2


class GarrisonServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.key_set = channel.unary_unary(
        '/garrison_server.GarrisonServer/key_set',
        request_serializer=garrison__pb2.KeySetRequest.SerializeToString,
        response_deserializer=garrison__pb2.KeySetResponse.FromString,
        )
    self.key_get = channel.unary_unary(
        '/garrison_server.GarrisonServer/key_get',
        request_serializer=garrison__pb2.KeyGetRequest.SerializeToString,
        response_deserializer=garrison__pb2.KeyGetResponse.FromString,
        )
    self.key_delete = channel.unary_unary(
        '/garrison_server.GarrisonServer/key_delete',
        request_serializer=garrison__pb2.KeyDeleteRequest.SerializeToString,
        response_deserializer=garrison__pb2.KeyDeleteResponse.FromString,
        )
    self.queue_pop = channel.unary_unary(
        '/garrison_server.GarrisonServer/queue_pop',
        request_serializer=garrison__pb2.QueuePopRequest.SerializeToString,
        response_deserializer=garrison__pb2.QueuePopResponse.FromString,
        )
    self.queue_push = channel.unary_unary(
        '/garrison_server.GarrisonServer/queue_push',
        request_serializer=garrison__pb2.QueuePushRequest.SerializeToString,
        response_deserializer=garrison__pb2.QueuePushResponse.FromString,
        )
    self.queue_delete = channel.unary_unary(
        '/garrison_server.GarrisonServer/queue_delete',
        request_serializer=garrison__pb2.QueueDeleteRequest.SerializeToString,
        response_deserializer=garrison__pb2.QueueDeleteResponse.FromString,
        )
    self.queue_length = channel.unary_unary(
        '/garrison_server.GarrisonServer/queue_length',
        request_serializer=garrison__pb2.QueueLengthRequest.SerializeToString,
        response_deserializer=garrison__pb2.QueueLengthResponse.FromString,
        )


class GarrisonServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def key_set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def key_get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def key_delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queue_pop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queue_push(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queue_delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queue_length(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GarrisonServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'key_set': grpc.unary_unary_rpc_method_handler(
          servicer.key_set,
          request_deserializer=garrison__pb2.KeySetRequest.FromString,
          response_serializer=garrison__pb2.KeySetResponse.SerializeToString,
      ),
      'key_get': grpc.unary_unary_rpc_method_handler(
          servicer.key_get,
          request_deserializer=garrison__pb2.KeyGetRequest.FromString,
          response_serializer=garrison__pb2.KeyGetResponse.SerializeToString,
      ),
      'key_delete': grpc.unary_unary_rpc_method_handler(
          servicer.key_delete,
          request_deserializer=garrison__pb2.KeyDeleteRequest.FromString,
          response_serializer=garrison__pb2.KeyDeleteResponse.SerializeToString,
      ),
      'queue_pop': grpc.unary_unary_rpc_method_handler(
          servicer.queue_pop,
          request_deserializer=garrison__pb2.QueuePopRequest.FromString,
          response_serializer=garrison__pb2.QueuePopResponse.SerializeToString,
      ),
      'queue_push': grpc.unary_unary_rpc_method_handler(
          servicer.queue_push,
          request_deserializer=garrison__pb2.QueuePushRequest.FromString,
          response_serializer=garrison__pb2.QueuePushResponse.SerializeToString,
      ),
      'queue_delete': grpc.unary_unary_rpc_method_handler(
          servicer.queue_delete,
          request_deserializer=garrison__pb2.QueueDeleteRequest.FromString,
          response_serializer=garrison__pb2.QueueDeleteResponse.SerializeToString,
      ),
      'queue_length': grpc.unary_unary_rpc_method_handler(
          servicer.queue_length,
          request_deserializer=garrison__pb2.QueueLengthRequest.FromString,
          response_serializer=garrison__pb2.QueueLengthResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'garrison_server.GarrisonServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
